# ----------------------------
# Makefile Options
# ----------------------------

NAME = MINESWEE
ICON = icon.png
DESCRIPTION = "Minesweeper by Kyle Gilbert"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
